openapi: 3.0.2
info:
  title: Metaplex API
  description: An API for interacting with the Solana NFT collections using Metaplex
  version: 1.0.0
servers:
  - url: http://localhost:300
paths:
  /api/handlers/solana-pay/qr/createMintCNFT:
    post:
      summary: createMintCNFT
      description: >-
        Mints a compressed NFT with the metadata uri. It does not need the rent or the treeAddress.
        Returns a QR code that the user can scan to approve the transaction.
      operationId: create_mint_cnft
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createMintCNFTRequest"
      responses:
        "200":
          description: Successful Response
  /api/metaplex/getCNFTRent:
    post:
      summary: getCNFTRent
      description: >-
        Returns the rent for creating a tree on mainnet and the maximum capacity.
      operationId: get_cnft_rent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/getCNFTRentRequest"
      responses:
        "200":
          description: Successful Response
  /api/metaplex/getPublicTreeAddresses:
    post:
      summary: getPublicTreeAddresses
      description: >-
        Shows the public tree addresses with available space.
      operationId: get_public_tree_addresses
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/getPublicTreeAddressesRequest"
      responses:
        "200":
          description: Successful Response
  /api/handlers/solana-pay/qr/createMintNFT:
    post:
      summary: createMintNFT
      description: >-
        Mints a normal uncompressed NFT with the given name, metadata uri and seller fees.
      operationId: create_mint_nft
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createMintNFTRequest"
      responses:
        "200":
          description: Successful Response
  /api/handlers/solana-pay/qr/createTransferAsset:
    post:
      summary: createTransferAsset
      description: >-
        Allows the user to send (transfer) compressed NFT to another account
      operationId: create_transfer_asset
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createTransferAssetRequest"
      responses:
        "200":
          description: Successful Response
  /api/handlers/solana-pay/qr/createBurnAsset:
    post:
      summary: createBurnAsset
      description: >-
        Allows the user to burn a compressed NFT
      operationId: create_burn_asset
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createBurnAssetRequest"
      responses:
        "200":
          description: Successful Response
components:
  schemas:
    getCNFTRentRequest:
      title: GetCNFTRentRequest
      type: object
      required:
        - treeSize
        - canopySize
      properties:
        treeSize:
          type: string
          enum:
            - "custom"
            - "small"
            - "medium"
            - "large"
        canopySize:
          type: string
          enum:
            - "custom"
            - "small"
            - "medium"
            - "large"
            - "none"
        customMaxDepth:
          type: number
          nullable: true
        customMaxBufferSize:
          type: number
          nullable: true
        customCanopySize:
          type: number
          nullable: true
    createMintCNFTRequest:
      title: CreateMintCNFTRequest
      type: object
      required:
        - metadataUri
      properties:
        metadataUri:
          type: "string"
          format: "uri"
          maxLength: 255
    createMintNFTRequest:
      title: CreateMintNFTRequest
      type: object
      required:
        - name
        - metadataUri
      properties:
        name:
          type: string
        metadataUri:
          type: string
          format: "uri"
          maxLength: 255
        sellerFee:
          type: number
    createTransferAssetRequest:
      type: object
      required:
        - destination
        - assetId
      properties:
        destination:
          type: string
        assetId:
          type: string
    createBurnAssetRequest:
      type: object
      required:
        - assetId
      properties:
        assetId:
          type: string
    getPublicTreeAddressesRequest:
      type: object
      properties: {}
