openapi: 3.1.0
info:
  title: HelloMoon Defi Summary API
  description: An API for querying information about defi protocols on Solana
  version: 1.0.0
servers:
  - url: https://chatgpt.solanalabs.com/api/helloMoon
paths:
  /defi/programNewUsers:
    post:
      summary: Shows new users of a program over time.
      description:
        Shows new users of a program over time. A new user is defined as the first time a publicKey
        has been a fee payer for this program address.
      operationId: query_program_new_users
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/programNewUsersRequest"
      responses:
        "200":
          description: Successful Response
components:
  schemas:
    stringComparisonOperator:
      type: string
      enum:
        - "="
        - "!="
        - ">"
        - "<"
        - ">="
      nullable: true
    nullableNumber:
      type: number
      nullable: true
    programNewUsersRequest:
      type: object
      required:
        - programId
      properties:
        programId:
          type: string
        day:
          type: string
          nullable: true
        limit:
          $ref: "#/components/schemas/nullableNumber"
